export const historix: {user1: string, user2: string, result:number, gameid:number}[] = [
    {
        user1:"tups",
        user2:"toups",
        result:1,
        gameid:1527
    },
    {
        user1:"tups1",
        user2:"toups1",
        result:1,
        gameid:1526
    },
    {
        user1:"tups2",
        user2:"toups2",
        result:0,
        gameid:1525
    },
    {
        user1:"tups3",
        user2:"toups3",
        result:0,
        gameid:1524
    },
    {
        user1:"tup4",
        user2:"toup4",
        result:1,
        gameid:1523
    },
    {
        user1:"tups5",
        user2:"toups5",
        result:1,
        gameid:1522
    },
    {
        user1:"tups3",
        user2:"toups3",
        result:0,
        gameid:1521
    },
    {
        user1:"tup4",
        user2:"toup4",
        result:1,
        gameid:1520
    },
    {
        user1:"tups5",
        user2:"toups5",
        result:1,
        gameid:1519
    },
    {
        user1:"tups3",
        user2:"toups3",
        result:0,
        gameid:1518
    },
    {
        user1:"tup4",
        user2:"toup4",
        result:1,
        gameid:1517
    },
    {
        user1:"tups5",
        user2:"toups5",
        result:1,
        gameid:1516
    },
    {
        user1:"tups3",
        user2:"toups3",
        result:0,
        gameid:1515
    },
    {
        user1:"tup4",
        user2:"toup4",
        result:1,
        gameid:1514 
    },
    {
        user1:"tups5",
        user2:"toups5",
        result:1,
        gameid:1513
    },
]